import ReactModernAuth from "./ReactModernAuth";
import Login from "./StandaloneLogin";
import SignUp from "./StandaloneSignUp";
import {
  Theme,
  AuthErrorType,
  AuthError,
  AuthResponse,
  OptionalSignUpData,
  RequiredSignUpData,
  SignUpData,
  AvatarField,
  TermsAcceptedField,
  TextFieldType,
  TextField,
  SignUpField,
  SignUpFields,
  FieldChangeHandlers,
  SignUpErrorType,
  SignUpError,
  SignUpResponse,
  OAuthProvider,
  OAuthProviders,
  SignUpHandler,
  AuthWithPasswordHandler,
  AuthWithOAuthHandler,
  RequestPasswordResetHandler,
  AuthConfig,
} from "./types";

export { ReactModernAuth, Login, SignUp };
export type {
  Theme,
  AuthErrorType,
  AuthError,
  AuthResponse,
  OptionalSignUpData,
  RequiredSignUpData,
  SignUpData,
  AvatarField,
  TermsAcceptedField,
  TextFieldType,
  TextField,
  SignUpField,
  SignUpFields,
  FieldChangeHandlers,
  SignUpErrorType,
  SignUpError,
  SignUpResponse,
  OAuthProvider,
  OAuthProviders,
  SignUpHandler,
  AuthWithPasswordHandler,
  AuthWithOAuthHandler,
  RequestPasswordResetHandler,
  AuthConfig,
};
